In [7]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print(PROJECT_ROOT)

%load_ext autoreload
%autoreload 2

g:\My Drive\Graduação e Pós\USP\MBA USP IA e Big Data\TCC\port_leadtime_prediction
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [35]:
import pandas as pd

from src.config.paths import RAW_ESTADIA_DIR
from src.ingestion.load_estadia import load_estadia_files
from src.processing.process_estadia import process_estadia

In [36]:
df_estadia_raw = load_estadia_files(input_dir=RAW_ESTADIA_DIR)
df_estadia_processed = process_estadia(df_estadia_raw)
df_estadia_processed

<string>:5: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
<string>:5: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
<string>:5: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
<string>:5: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.

,duv,porto_bitrigrama,porto_nome,embarcacao_imo,embarcacao_inscricao,embarcacao_nome,tripulantes_embarque,tripulantes_transito,tripulantes_desembarque,tripulantes_total,...,estadia_atracacao,estadia_desatracacao,estadia_saida_do_porto,porto_origem_bitrigrama,porto_origem_nome,porto_destino_bitrigrama,porto_destino_nome,source_file,ano_referencia,mes_referencia
0,12022,BRSSZ,SANTOS,9634854.0,NaN,ORION GLOBE,0.0,21,0,21,...,2022-01-20 20:20:00+00:00,2022-01-24 00:52:00+00:00,2022-01-24 00:52:00+00:00,SGSIN,SINGAPURA (SINGAPORE),SGSIN,SINGAPURA (SINGAPORE),estadia_embarcacao.csv,2022.0,1.0
1,22022,BRSSZ,SANTOS,9699359.0,NaN,COPENHAGEN EAGLE,0.0,19,0,19,...,2022-02-25 08:05:00+00:00,2022-02-28 16:45:00+00:00,2022-02-28 16:45:00+00:00,SGSIN,SINGAPURA (SINGAPORE),BRPNG,PARANAGUA,estadia_embarcacao.csv,2022.0,1.0
2,32022,BRSSZ,SANTOS,9686273.0,NaN,CEPHEUS OCEAN,0.0,19,0,19,...,2022-02-28 23:25:00+00:00,NaT,NaT,RU006,UST - LUGA,NaN,NaN,estadia_embarcacao.csv,2022.0,1.0
3,62022,BRRJ022,PORTO DO AÇU,9644158.0,NaN,ZARAPITO,0.0,15,0,15,...,2022-01-01 11:00:00+00:00,2022-01-03 13:27:00+00:00,2022-01-03 13:27:00+00:00,BRRIO,RIO DE JANEIRO,BRRIO,RIO DE JANEIRO,estadia_embarcacao.csv,2022.0,1.0
4,72022,BRMEA001,TERMINAL PETROBRÁS - MACAÉ - RJ,9618757.0,3813885801,MAR LIMPO II,0.0,13,0,13,...,2022-01-03 09:50:00+00:00,2022-01-04 06:00:00+00:00,2022-01-04 20:40:00+00:00,BRRIO,RIO DE JANEIRO,BRMEA001,TERMINAL PETROBRÁS - MACAÉ - RJ,estadia_embarcacao.csv,2022.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162031,610152025,BRNTR,NITERÓI,9763772.0,4430488649,STIM STAR BRASIL,0.0,17,0,17,...,2025-12-31 20:00:00+00:00,2026-01-03 21:10:00+00:00,2026-01-03 21:10:00+00:00,BRMEA001,TERMINAL PETROBRÁS - MACAÉ - RJ,BRRJ022,PORTO DO AÇU,estadia_embarcacao.csv,2025.0,12.0
162032,610182025,BRRIO,RIO DE JANEIRO,9759496.0,4430489777,STARNAV VOLANS,0.0,15,0,15,...,2025-12-31 20:50:00+00:00,2026-01-04 13:30:00+00:00,2026-01-04 13:30:00+00:00,BRRIO,RIO DE JANEIRO,BRRIO,RIO DE JANEIRO,estadia_embarcacao.csv,2025.0,12.0
162033,610312025,BRRIO,RIO DE JANEIRO,9357169.0,3810518310,ASSO VENTISETTE,0.0,14,0,14,...,2025-12-31 23:25:00+00:00,2026-01-04 19:10:00+00:00,2026-01-04 19:10:00+00:00,BRRIO,RIO DE JANEIRO,BRRIO,RIO DE JANEIRO,estadia_embarcacao.csv,2025.0,12.0
162034,610382025,BRRIO,RIO DE JANEIRO,9497127.0,4430138389,CAMPOS CONTENDER,0.0,16,0,16,...,2025-12-31 21:30:00+00:00,2026-01-03 09:35:00+00:00,2026-01-03 09:35:00+00:00,BRNTR,NITERÓI,BRRIO,RIO DE JANEIRO,estadia_embarcacao.csv,2025.0,12.0
162035,610772025,BRRIO,RIO DE JANEIRO,9530008.0,NaN,JACK EDWARDS (BAND. GREYLIST TOKYO MOU),0.0,15,0,15,...,2025-12-31 23:30:00+00:00,2026-01-02 22:05:00+00:00,2026-01-02 22:05:00+00:00,BRRIO,RIO DE JANEIRO,BRRIO,RIO DE JANEIRO,estadia_embarcacao.csv,2025.0,12.0

In [37]:
df_estadia_processed.drop_duplicates(inplace=True)
df_estadia_processed

,duv,porto_bitrigrama,porto_nome,embarcacao_imo,embarcacao_inscricao,embarcacao_nome,tripulantes_embarque,tripulantes_transito,tripulantes_desembarque,tripulantes_total,...,estadia_atracacao,estadia_desatracacao,estadia_saida_do_porto,porto_origem_bitrigrama,porto_origem_nome,porto_destino_bitrigrama,porto_destino_nome,source_file,ano_referencia,mes_referencia
0,12022,BRSSZ,SANTOS,9634854.0,NaN,ORION GLOBE,0.0,21,0,21,...,2022-01-20 20:20:00+00:00,2022-01-24 00:52:00+00:00,2022-01-24 00:52:00+00:00,SGSIN,SINGAPURA (SINGAPORE),SGSIN,SINGAPURA (SINGAPORE),estadia_embarcacao.csv,2022.0,1.0
1,22022,BRSSZ,SANTOS,9699359.0,NaN,COPENHAGEN EAGLE,0.0,19,0,19,...,2022-02-25 08:05:00+00:00,2022-02-28 16:45:00+00:00,2022-02-28 16:45:00+00:00,SGSIN,SINGAPURA (SINGAPORE),BRPNG,PARANAGUA,estadia_embarcacao.csv,2022.0,1.0
2,32022,BRSSZ,SANTOS,9686273.0,NaN,CEPHEUS OCEAN,0.0,19,0,19,...,2022-02-28 23:25:00+00:00,NaT,NaT,RU006,UST - LUGA,NaN,NaN,estadia_embarcacao.csv,2022.0,1.0
3,62022,BRRJ022,PORTO DO AÇU,9644158.0,NaN,ZARAPITO,0.0,15,0,15,...,2022-01-01 11:00:00+00:00,2022-01-03 13:27:00+00:00,2022-01-03 13:27:00+00:00,BRRIO,RIO DE JANEIRO,BRRIO,RIO DE JANEIRO,estadia_embarcacao.csv,2022.0,1.0
4,72022,BRMEA001,TERMINAL PETROBRÁS - MACAÉ - RJ,9618757.0,3813885801,MAR LIMPO II,0.0,13,0,13,...,2022-01-03 09:50:00+00:00,2022-01-04 06:00:00+00:00,2022-01-04 20:40:00+00:00,BRRIO,RIO DE JANEIRO,BRMEA001,TERMINAL PETROBRÁS - MACAÉ - RJ,estadia_embarcacao.csv,2022.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162031,610152025,BRNTR,NITERÓI,9763772.0,4430488649,STIM STAR BRASIL,0.0,17,0,17,...,2025-12-31 20:00:00+00:00,2026-01-03 21:10:00+00:00,2026-01-03 21:10:00+00:00,BRMEA001,TERMINAL PETROBRÁS - MACAÉ - RJ,BRRJ022,PORTO DO AÇU,estadia_embarcacao.csv,2025.0,12.0
162032,610182025,BRRIO,RIO DE JANEIRO,9759496.0,4430489777,STARNAV VOLANS,0.0,15,0,15,...,2025-12-31 20:50:00+00:00,2026-01-04 13:30:00+00:00,2026-01-04 13:30:00+00:00,BRRIO,RIO DE JANEIRO,BRRIO,RIO DE JANEIRO,estadia_embarcacao.csv,2025.0,12.0
162033,610312025,BRRIO,RIO DE JANEIRO,9357169.0,3810518310,ASSO VENTISETTE,0.0,14,0,14,...,2025-12-31 23:25:00+00:00,2026-01-04 19:10:00+00:00,2026-01-04 19:10:00+00:00,BRRIO,RIO DE JANEIRO,BRRIO,RIO DE JANEIRO,estadia_embarcacao.csv,2025.0,12.0
162034,610382025,BRRIO,RIO DE JANEIRO,9497127.0,4430138389,CAMPOS CONTENDER,0.0,16,0,16,...,2025-12-31 21:30:00+00:00,2026-01-03 09:35:00+00:00,2026-01-03 09:35:00+00:00,BRNTR,NITERÓI,BRRIO,RIO DE JANEIRO,estadia_embarcacao.csv,2025.0,12.0
162035,610772025,BRRIO,RIO DE JANEIRO,9530008.0,NaN,JACK EDWARDS (BAND. GREYLIST TOKYO MOU),0.0,15,0,15,...,2025-12-31 23:30:00+00:00,2026-01-02 22:05:00+00:00,2026-01-02 22:05:00+00:00,BRRIO,RIO DE JANEIRO,BRRIO,RIO DE JANEIRO,estadia_embarcacao.csv,2025.0,12.0