In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print(PROJECT_ROOT)

%load_ext autoreload
%autoreload 2

g:\My Drive\Graduação e Pós\USP\MBA USP IA e Big Data\TCC\port_leadtime_prediction

In [2]:
import pandas as pd

import src.config.paths as paths
from src.ingestion.load_estadia import load_estadia_files
from src.processing.process_estadia import process_estadia

from src.ingestion.load_porto import load_porto_files
from src.processing.process_porto import process_porto

from src.ingestion.load_meteorologia import load_meteorologia_files
from src.processing.process_meteorologia import process_meteorologia

In [3]:
df_estadia_raw = load_estadia_files(input_dir=paths.RAW_ESTADIA_DIR)
df_estadia_processed = process_estadia(df_estadia_raw)
df_estadia_processed

,duv,porto_bitrigrama,porto_nome,embarcacao_imo,embarcacao_inscricao,embarcacao_nome,tripulantes_embarque,tripulantes_transito,tripulantes_desembarque,tripulantes_total,...,estadia_chegada_no_porto,estadia_atracacao,estadia_desatracacao,estadia_saida_do_porto,porto_origem_bitrigrama,porto_origem_nome,porto_destino_bitrigrama,porto_destino_nome,ano_referencia,mes_referencia
0,12022,BRSSZ,SANTOS,9634854.0,NaN,ORION GLOBE,0.0,21,0,21,...,2022-01-13 09:00:00+00:00,2022-01-20 20:20:00+00:00,2022-01-24 00:52:00+00:00,2022-01-24 00:52:00+00:00,SGSIN,SINGAPURA (SINGAPORE),SGSIN,SINGAPURA (SINGAPORE),2022.0,1.0
1,22022,BRSSZ,SANTOS,9699359.0,NaN,COPENHAGEN EAGLE,0.0,19,0,19,...,2022-01-15 12:05:00+00:00,2022-02-25 08:05:00+00:00,2022-02-28 16:45:00+00:00,2022-02-28 16:45:00+00:00,SGSIN,SINGAPURA (SINGAPORE),BRPNG,PARANAGUA,2022.0,1.0
2,32022,BRSSZ,SANTOS,9686273.0,NaN,CEPHEUS OCEAN,0.0,19,0,19,...,2022-01-19 13:00:00+00:00,2022-02-28 23:25:00+00:00,NaT,NaT,RU006,UST - LUGA,NaN,NaN,2022.0,1.0
3,62022,BRRJ022,PORTO DO AÇU,9644158.0,NaN,ZARAPITO,0.0,15,0,15,...,2022-01-01 11:00:00+00:00,2022-01-01 11:00:00+00:00,2022-01-03 13:27:00+00:00,2022-01-03 13:27:00+00:00,BRRIO,RIO DE JANEIRO,BRRIO,RIO DE JANEIRO,2022.0,1.0
4,72022,BRMEA001,TERMINAL PETROBRÁS - MACAÉ - RJ,9618757.0,3813885801,MAR LIMPO II,0.0,13,0,13,...,2022-01-01 20:45:00+00:00,2022-01-03 09:50:00+00:00,2022-01-04 06:00:00+00:00,2022-01-04 20:40:00+00:00,BRRIO,RIO DE JANEIRO,BRMEA001,TERMINAL PETROBRÁS - MACAÉ - RJ,2022.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162031,610152025,BRNTR,NITERÓI,9763772.0,4430488649,STIM STAR BRASIL,0.0,17,0,17,...,2025-12-31 20:00:00+00:00,2025-12-31 20:00:00+00:00,2026-01-03 21:10:00+00:00,2026-01-03 21:10:00+00:00,BRMEA001,TERMINAL PETROBRÁS - MACAÉ - RJ,BRRJ022,PORTO DO AÇU,2025.0,12.0
162032,610182025,BRRIO,RIO DE JANEIRO,9759496.0,4430489777,STARNAV VOLANS,0.0,15,0,15,...,2025-12-31 20:50:00+00:00,2025-12-31 20:50:00+00:00,2026-01-04 13:30:00+00:00,2026-01-04 13:30:00+00:00,BRRIO,RIO DE JANEIRO,BRRIO,RIO DE JANEIRO,2025.0,12.0
162033,610312025,BRRIO,RIO DE JANEIRO,9357169.0,3810518310,ASSO VENTISETTE,0.0,14,0,14,...,2025-12-31 23:25:00+00:00,2025-12-31 23:25:00+00:00,2026-01-04 19:10:00+00:00,2026-01-04 19:10:00+00:00,BRRIO,RIO DE JANEIRO,BRRIO,RIO DE JANEIRO,2025.0,12.0
162034,610382025,BRRIO,RIO DE JANEIRO,9497127.0,4430138389,CAMPOS CONTENDER,0.0,16,0,16,...,2025-12-31 21:30:00+00:00,2025-12-31 21:30:00+00:00,2026-01-03 09:35:00+00:00,2026-01-03 09:35:00+00:00,BRNTR,NITERÓI,BRRIO,RIO DE JANEIRO,2025.0,12.0
162035,610772025,BRRIO,RIO DE JANEIRO,9530008.0,NaN,JACK EDWARDS (BAND. GREYLIST TOKYO MOU),0.0,15,0,15,...,2025-12-31 23:30:00+00:00,2025-12-31 23:30:00+00:00,2026-01-02 22:05:00+00:00,2026-01-02 22:05:00+00:00,BRRIO,RIO DE JANEIRO,BRRIO,RIO DE JANEIRO,2025.0,12.0

In [4]:
df_estadia_processed.drop_duplicates(inplace=True)
df_estadia_processed

,duv,porto_bitrigrama,porto_nome,embarcacao_imo,embarcacao_inscricao,embarcacao_nome,tripulantes_embarque,tripulantes_transito,tripulantes_desembarque,tripulantes_total,...,estadia_chegada_no_porto,estadia_atracacao,estadia_desatracacao,estadia_saida_do_porto,porto_origem_bitrigrama,porto_origem_nome,porto_destino_bitrigrama,porto_destino_nome,ano_referencia,mes_referencia
0,12022,BRSSZ,SANTOS,9634854.0,NaN,ORION GLOBE,0.0,21,0,21,...,2022-01-13 09:00:00+00:00,2022-01-20 20:20:00+00:00,2022-01-24 00:52:00+00:00,2022-01-24 00:52:00+00:00,SGSIN,SINGAPURA (SINGAPORE),SGSIN,SINGAPURA (SINGAPORE),2022.0,1.0
1,22022,BRSSZ,SANTOS,9699359.0,NaN,COPENHAGEN EAGLE,0.0,19,0,19,...,2022-01-15 12:05:00+00:00,2022-02-25 08:05:00+00:00,2022-02-28 16:45:00+00:00,2022-02-28 16:45:00+00:00,SGSIN,SINGAPURA (SINGAPORE),BRPNG,PARANAGUA,2022.0,1.0
2,32022,BRSSZ,SANTOS,9686273.0,NaN,CEPHEUS OCEAN,0.0,19,0,19,...,2022-01-19 13:00:00+00:00,2022-02-28 23:25:00+00:00,NaT,NaT,RU006,UST - LUGA,NaN,NaN,2022.0,1.0
3,62022,BRRJ022,PORTO DO AÇU,9644158.0,NaN,ZARAPITO,0.0,15,0,15,...,2022-01-01 11:00:00+00:00,2022-01-01 11:00:00+00:00,2022-01-03 13:27:00+00:00,2022-01-03 13:27:00+00:00,BRRIO,RIO DE JANEIRO,BRRIO,RIO DE JANEIRO,2022.0,1.0
4,72022,BRMEA001,TERMINAL PETROBRÁS - MACAÉ - RJ,9618757.0,3813885801,MAR LIMPO II,0.0,13,0,13,...,2022-01-01 20:45:00+00:00,2022-01-03 09:50:00+00:00,2022-01-04 06:00:00+00:00,2022-01-04 20:40:00+00:00,BRRIO,RIO DE JANEIRO,BRMEA001,TERMINAL PETROBRÁS - MACAÉ - RJ,2022.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162031,610152025,BRNTR,NITERÓI,9763772.0,4430488649,STIM STAR BRASIL,0.0,17,0,17,...,2025-12-31 20:00:00+00:00,2025-12-31 20:00:00+00:00,2026-01-03 21:10:00+00:00,2026-01-03 21:10:00+00:00,BRMEA001,TERMINAL PETROBRÁS - MACAÉ - RJ,BRRJ022,PORTO DO AÇU,2025.0,12.0
162032,610182025,BRRIO,RIO DE JANEIRO,9759496.0,4430489777,STARNAV VOLANS,0.0,15,0,15,...,2025-12-31 20:50:00+00:00,2025-12-31 20:50:00+00:00,2026-01-04 13:30:00+00:00,2026-01-04 13:30:00+00:00,BRRIO,RIO DE JANEIRO,BRRIO,RIO DE JANEIRO,2025.0,12.0
162033,610312025,BRRIO,RIO DE JANEIRO,9357169.0,3810518310,ASSO VENTISETTE,0.0,14,0,14,...,2025-12-31 23:25:00+00:00,2025-12-31 23:25:00+00:00,2026-01-04 19:10:00+00:00,2026-01-04 19:10:00+00:00,BRRIO,RIO DE JANEIRO,BRRIO,RIO DE JANEIRO,2025.0,12.0
162034,610382025,BRRIO,RIO DE JANEIRO,9497127.0,4430138389,CAMPOS CONTENDER,0.0,16,0,16,...,2025-12-31 21:30:00+00:00,2025-12-31 21:30:00+00:00,2026-01-03 09:35:00+00:00,2026-01-03 09:35:00+00:00,BRNTR,NITERÓI,BRRIO,RIO DE JANEIRO,2025.0,12.0
162035,610772025,BRRIO,RIO DE JANEIRO,9530008.0,NaN,JACK EDWARDS (BAND. GREYLIST TOKYO MOU),0.0,15,0,15,...,2025-12-31 23:30:00+00:00,2025-12-31 23:30:00+00:00,2026-01-02 22:05:00+00:00,2026-01-02 22:05:00+00:00,BRRIO,RIO DE JANEIRO,BRRIO,RIO DE JANEIRO,2025.0,12.0

In [5]:
df_porto_raw = load_porto_files(input_dir=paths.RAW_PORTO_DIR)
df_porto_processed = process_porto(df_porto_raw)

df_porto_processed

,porto,nome_porto,cidade,estado,regiao,latitude,longitude
0,BR052001,TERMINAL FLUVIAL DE JURUTI,JURITI,PA,NORTE,-2.173782,-56.105980
1,BR147001,TERMINAL PORTUÁRIO FLUVIAL - COPESUL,TRIUNFO,RS,SUL,-29.948610,-51.623888
2,BR252002,TERM AQUAVIARIO DE GUAMARE - 3R OPERAÇÕES MARI...,GUAMARÉ,RN,NORDESTE,-5.106387,-36.317918
3,BR302002,TUP NSR,NOVA SANTA RITA,RS,SUL,-29.931204,-51.282781
4,BR400001,TERMINAL DE MINERIO FERROPORT - PORTO DO AÇU,SÃO JOÃO DA BARRA,RJ,SUDESTE,-21.814444,-40.998333
...,...,...,...,...,...,...,...
120,BRSE003,CELSE TERMINAL DE REGASEIFICAÇÃO,BARRA DOS COQUEIROS,SE,NORDESTE,-10.843889,-36.919167
121,BRSFS002,TERMINAL DA BABITONGA,SÃO FRANCISCO DO SUL,SC,SUL,-26.217361,-48.500971
122,BRVDC004,TERMINAL FLUVIAL RIO CAPIM CAULIM S/A,BARCARENA,PA,NORTE,-1.496110,-48.727221
123,BRVLL,PORTO DE LAGUNA,LAGUNA,SC,SUL,-28.497206,-48.769000
124,BRBA004,TERMINAL DE CARAVELAS,CARAVELAS,BA,NORDESTE,-17.751388,-39.216388

In [6]:
df_meteorologia_raw = load_meteorologia_files(input_dir=paths.RAW_METEOROLOGIA_DIR)
df_meteorologia_processed = process_meteorologia(df_meteorologia_raw)

df_meteorologia_processed

,latitude,longitude,date,temperature_2m_mean,temperature_2m_max,temperature_2m_min,precipitation_sum,rain_sum,precipitation_hours,wind_speed_10m_max,wind_gusts_10m_max,wind_direction_10m_dominant
0,-2.173782,-56.105980,2021-06-15,26.7,30.2,24.3,6.1,6.1,11.0,7.8,27.7,117
1,-2.173782,-56.105980,2021-06-16,26.4,29.8,23.7,19.1,19.1,15.0,8.3,30.2,93
2,-2.173782,-56.105980,2021-06-17,26.8,30.1,23.1,3.6,3.6,12.0,7.5,25.9,37
3,-2.173782,-56.105980,2021-06-18,27.1,30.8,23.3,2.3,2.3,4.0,8.4,27.4,54
4,-2.173782,-56.105980,2021-06-19,26.9,30.0,24.4,14.0,14.0,5.0,16.9,39.2,81
...,...,...,...,...,...,...,...,...,...,...,...,...
167094,-12.753888,-38.624305,2025-08-27,23.4,24.5,22.1,5.5,5.5,22.0,18.5,29.2,139
167095,-12.753888,-38.624305,2025-08-28,24.0,25.2,22.8,2.8,2.8,20.0,19.5,30.2,143
167096,-12.753888,-38.624305,2025-08-29,24.0,25.6,22.5,2.4,2.4,17.0,20.5,30.2,127
167097,-12.753888,-38.624305,2025-08-30,23.7,25.2,22.5,3.3,3.3,21.0,20.5,29.9,152
167098,-12.753888,-38.624305,2025-08-31,23.6,24.7,22.1,4.5,4.5,19.0,18.6,28.8,126