In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print(PROJECT_ROOT)

%load_ext autoreload
%autoreload 2

g:\My Drive\Graduação e Pós\USP\MBA USP IA e Big Data\TCC\port_leadtime_prediction

In [2]:
import pandas as pd

from src.config.paths import RAW_ESTADIA_DIR
from src.ingestion.load_estadia import load_estadia_files
from src.processing.process_estadia import process_estadia

In [3]:
df_estadia_raw = load_estadia_files(input_dir=RAW_ESTADIA_DIR)

print(df_estadia_raw.shape)

(162036, 24)

In [4]:
df_estadia_raw

,DUV,Porto - Bitrigrama,Porto - Nome,Embarcacao - IMO,Embarcacao - Inscricao,Embarcacao - Nome,Tripulantes - Embarque,Tripulantes - Transito,Tripulantes - Desembarque,Tripulantes - Total,...,Estadia - Motivos Atracacao,Estadia - Chegada no Porto,Estadia - Atracacao,Estadia - Desatracacao,Estadia - Saida do Porto,Porto Origem - Bitrigrama,Porto Origem - Nome,Porto Destino - Bitrigrama,Porto Destino - Nome,source_file
0,12022,BRSSZ,SANTOS ...,9634854,,ORION GLOBE,0.0,21,0,21,...,Carga ...,2022-01-13 06:00:00-03,2022-01-20 17:20:00-03,2022-01-23 21:52:00-03,2022-01-23 21:52:00-03,SGSIN,SINGAPURA (SINGAPORE) ...,SGSIN,SINGAPURA (SINGAPORE),2022-01.csv
1,22022,BRSSZ,SANTOS ...,9699359,,COPENHAGEN EAGLE,0.0,19,0,19,...,Descarga ...,2022-01-15 09:05:00-03,2022-02-25 05:05:00-03,2022-02-28 13:45:00-03,2022-02-28 13:45:00-03,SGSIN,SINGAPURA (SINGAPORE) ...,BRPNG,PARANAGUA,2022-01.csv
2,32022,BRSSZ,SANTOS ...,9686273,,CEPHEUS OCEAN,0.0,19,0,19,...,Descarga ...,2022-01-19 10:00:00-03,2022-02-28 20:25:00-03,,,RU006,UST - LUGA ...,,,2022-01.csv
3,62022,BRRJ022,PORTO DO AÇU ...,9644158,,ZARAPITO,0.0,15,0,15,...,Off-shore ...,2022-01-01 08:00:00-03,2022-01-01 08:00:00-03,2022-01-03 10:27:00-03,2022-01-03 10:27:00-03,BRRIO,RIO DE JANEIRO ...,BRRIO,RIO DE JANEIRO,2022-01.csv
4,72022,BRMEA001,TERMINAL PETROBRÁS - MACAÉ - RJ ...,9618757,3813885801,MAR LIMPO II,0.0,13,0,13,...,"Desembarque/Embarque de Passageiros,Off-shore...",2022-01-01 17:45:00-03,2022-01-03 06:50:00-03,2022-01-04 03:00:00-03,2022-01-04 17:40:00-03,BRRIO,RIO DE JANEIRO ...,BRMEA001,TERMINAL PETROBRÁS - MACAÉ - RJ,2022-01.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162031,610152025,BRNTR,NITERÓI,9763772.0,4430488649,STIM STAR BRASIL,0.0,17,0,17,...,Off-shore,2025-12-31 17:00:00.0000000,2025-12-31 17:00:00.0000000,2026-01-03 18:10:00.0000000,2026-01-03 18:10:00.0000000,BRMEA001,TERMINAL PETROBRÁS - MACAÉ - RJ,BRRJ022,PORTO DO AÇU,2025-12.csv
162032,610182025,BRRIO,RIO DE JANEIRO,9759496.0,4430489777,STARNAV VOLANS,0.0,15,0,15,...,Off-shore,2025-12-31 17:50:00.0000000,2025-12-31 17:50:00.0000000,2026-01-04 10:30:00.0000000,2026-01-04 10:30:00.0000000,BRRIO,RIO DE JANEIRO,BRRIO,RIO DE JANEIRO,2025-12.csv
162033,610312025,BRRIO,RIO DE JANEIRO,9357169.0,3810518310,ASSO VENTISETTE,0.0,14,0,14,...,Off-shore,2025-12-31 20:25:00.0000000,2025-12-31 20:25:00.0000000,2026-01-04 16:10:00.0000000,2026-01-04 16:10:00.0000000,BRRIO,RIO DE JANEIRO,BRRIO,RIO DE JANEIRO,2025-12.csv
162034,610382025,BRRIO,RIO DE JANEIRO,9497127.0,4430138389,CAMPOS CONTENDER,0.0,16,0,16,...,Off-shore,2025-12-31 18:30:00.0000000,2025-12-31 18:30:00.0000000,2026-01-03 06:35:00.0000000,2026-01-03 06:35:00.0000000,BRNTR,NITERÓI,BRRIO,RIO DE JANEIRO,2025-12.csv
162035,610772025,BRRIO,RIO DE JANEIRO,9530008.0,NaN,JACK EDWARDS (BAND. GREYLIST TOKYO MOU),0.0,15,0,15,...,Off-shore,2025-12-31 20:30:00.0000000,2025-12-31 20:30:00.0000000,2026-01-02 19:05:00.0000000,2026-01-02 19:05:00.0000000,BRRIO,RIO DE JANEIRO,BRRIO,RIO DE JANEIRO,2025-12.csv

In [5]:
df_estadia_raw.drop_duplicates()

,DUV,Porto - Bitrigrama,Porto - Nome,Embarcacao - IMO,Embarcacao - Inscricao,Embarcacao - Nome,Tripulantes - Embarque,Tripulantes - Transito,Tripulantes - Desembarque,Tripulantes - Total,...,Estadia - Motivos Atracacao,Estadia - Chegada no Porto,Estadia - Atracacao,Estadia - Desatracacao,Estadia - Saida do Porto,Porto Origem - Bitrigrama,Porto Origem - Nome,Porto Destino - Bitrigrama,Porto Destino - Nome,source_file
0,12022,BRSSZ,SANTOS ...,9634854,,ORION GLOBE,0.0,21,0,21,...,Carga ...,2022-01-13 06:00:00-03,2022-01-20 17:20:00-03,2022-01-23 21:52:00-03,2022-01-23 21:52:00-03,SGSIN,SINGAPURA (SINGAPORE) ...,SGSIN,SINGAPURA (SINGAPORE),2022-01.csv
1,22022,BRSSZ,SANTOS ...,9699359,,COPENHAGEN EAGLE,0.0,19,0,19,...,Descarga ...,2022-01-15 09:05:00-03,2022-02-25 05:05:00-03,2022-02-28 13:45:00-03,2022-02-28 13:45:00-03,SGSIN,SINGAPURA (SINGAPORE) ...,BRPNG,PARANAGUA,2022-01.csv
2,32022,BRSSZ,SANTOS ...,9686273,,CEPHEUS OCEAN,0.0,19,0,19,...,Descarga ...,2022-01-19 10:00:00-03,2022-02-28 20:25:00-03,,,RU006,UST - LUGA ...,,,2022-01.csv
3,62022,BRRJ022,PORTO DO AÇU ...,9644158,,ZARAPITO,0.0,15,0,15,...,Off-shore ...,2022-01-01 08:00:00-03,2022-01-01 08:00:00-03,2022-01-03 10:27:00-03,2022-01-03 10:27:00-03,BRRIO,RIO DE JANEIRO ...,BRRIO,RIO DE JANEIRO,2022-01.csv
4,72022,BRMEA001,TERMINAL PETROBRÁS - MACAÉ - RJ ...,9618757,3813885801,MAR LIMPO II,0.0,13,0,13,...,"Desembarque/Embarque de Passageiros,Off-shore...",2022-01-01 17:45:00-03,2022-01-03 06:50:00-03,2022-01-04 03:00:00-03,2022-01-04 17:40:00-03,BRRIO,RIO DE JANEIRO ...,BRMEA001,TERMINAL PETROBRÁS - MACAÉ - RJ,2022-01.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162031,610152025,BRNTR,NITERÓI,9763772.0,4430488649,STIM STAR BRASIL,0.0,17,0,17,...,Off-shore,2025-12-31 17:00:00.0000000,2025-12-31 17:00:00.0000000,2026-01-03 18:10:00.0000000,2026-01-03 18:10:00.0000000,BRMEA001,TERMINAL PETROBRÁS - MACAÉ - RJ,BRRJ022,PORTO DO AÇU,2025-12.csv
162032,610182025,BRRIO,RIO DE JANEIRO,9759496.0,4430489777,STARNAV VOLANS,0.0,15,0,15,...,Off-shore,2025-12-31 17:50:00.0000000,2025-12-31 17:50:00.0000000,2026-01-04 10:30:00.0000000,2026-01-04 10:30:00.0000000,BRRIO,RIO DE JANEIRO,BRRIO,RIO DE JANEIRO,2025-12.csv
162033,610312025,BRRIO,RIO DE JANEIRO,9357169.0,3810518310,ASSO VENTISETTE,0.0,14,0,14,...,Off-shore,2025-12-31 20:25:00.0000000,2025-12-31 20:25:00.0000000,2026-01-04 16:10:00.0000000,2026-01-04 16:10:00.0000000,BRRIO,RIO DE JANEIRO,BRRIO,RIO DE JANEIRO,2025-12.csv
162034,610382025,BRRIO,RIO DE JANEIRO,9497127.0,4430138389,CAMPOS CONTENDER,0.0,16,0,16,...,Off-shore,2025-12-31 18:30:00.0000000,2025-12-31 18:30:00.0000000,2026-01-03 06:35:00.0000000,2026-01-03 06:35:00.0000000,BRNTR,NITERÓI,BRRIO,RIO DE JANEIRO,2025-12.csv
162035,610772025,BRRIO,RIO DE JANEIRO,9530008.0,NaN,JACK EDWARDS (BAND. GREYLIST TOKYO MOU),0.0,15,0,15,...,Off-shore,2025-12-31 20:30:00.0000000,2025-12-31 20:30:00.0000000,2026-01-02 19:05:00.0000000,2026-01-02 19:05:00.0000000,BRRIO,RIO DE JANEIRO,BRRIO,RIO DE JANEIRO,2025-12.csv

In [6]:
df_estadia_processed = process_estadia(df_estadia_raw)

print(df_estadia_processed.shape)
df_estadia_processed.head()

(162036, 24)

,duv,porto_-_bitrigrama,porto_-_nome,embarcacao_-_imo,embarcacao_-_inscricao,embarcacao_-_nome,tripulantes_-_embarque,tripulantes_-_transito,tripulantes_-_desembarque,tripulantes_-_total,...,estadia_-_motivos_atracacao,estadia_-_chegada_no_porto,estadia_-_atracacao,estadia_-_desatracacao,estadia_-_saida_do_porto,porto_origem_-_bitrigrama,porto_origem_-_nome,porto_destino_-_bitrigrama,porto_destino_-_nome,source_file
0,12022,BRSSZ,SANTOS ...,9634854,,ORION GLOBE,0.0,21,0,21,...,Carga ...,2022-01-13 06:00:00-03,2022-01-20 17:20:00-03,2022-01-23 21:52:00-03,2022-01-23 21:52:00-03,SGSIN,SINGAPURA (SINGAPORE) ...,SGSIN,SINGAPURA (SINGAPORE),2022-01.csv
1,22022,BRSSZ,SANTOS ...,9699359,,COPENHAGEN EAGLE,0.0,19,0,19,...,Descarga ...,2022-01-15 09:05:00-03,2022-02-25 05:05:00-03,2022-02-28 13:45:00-03,2022-02-28 13:45:00-03,SGSIN,SINGAPURA (SINGAPORE) ...,BRPNG,PARANAGUA,2022-01.csv
2,32022,BRSSZ,SANTOS ...,9686273,,CEPHEUS OCEAN,0.0,19,0,19,...,Descarga ...,2022-01-19 10:00:00-03,2022-02-28 20:25:00-03,,,RU006,UST - LUGA ...,,,2022-01.csv
3,62022,BRRJ022,PORTO DO AÇU ...,9644158,,ZARAPITO,0.0,15,0,15,...,Off-shore ...,2022-01-01 08:00:00-03,2022-01-01 08:00:00-03,2022-01-03 10:27:00-03,2022-01-03 10:27:00-03,BRRIO,RIO DE JANEIRO ...,BRRIO,RIO DE JANEIRO,2022-01.csv
4,72022,BRMEA001,TERMINAL PETROBRÁS - MACAÉ - RJ ...,9618757,3813885801,MAR LIMPO II,0.0,13,0,13,...,"Desembarque/Embarque de Passageiros,Off-shore...",2022-01-01 17:45:00-03,2022-01-03 06:50:00-03,2022-01-04 03:00:00-03,2022-01-04 17:40:00-03,BRRIO,RIO DE JANEIRO ...,BRMEA001,TERMINAL PETROBRÁS - MACAÉ - RJ,2022-01.csv